(deftheme railscast-modified "Created 2017-08-18.")
(custom-theme-set-faces 'railscast-modified
                        '(default ((t (:family "WanpakuRuikaMono" :foundry "nil"
                                               :width normal
                                               :height 140
                                               :weight thin
                                               :slant normal
                                               :underline nil
                                               :overline nil
                                               :strike-through nil
                                               :box nil
                                               :inverse-video nil
                                               :foreground "#E6E1DC"
                                               :background "#2b2b2b"
                                               :stipple nil
                                               :inherit nil))))
                        '(cursor ((t (:foreground "#5A647E"))))
                        '(fixed-pitch ((t (:family "Monospace"))))
                        '(variable-pitch ((((type w32))
                                           (:font "-outline-Arial-normal-normal-normal-sans-*-*-*-*-p-*-iso8859-1"))
                                          (t (:family "Sans Serif"))))
                        '(escape-glyph ((((background dark))
                                         (:foreground "cyan"))
                                        (((type pc))
                                         (:foreground "magenta"))
                                        (t (:foreground "brown"))))
                        '(minibuffer-prompt ((t (:foreground "#FF6600" :bold t))))
                        '(highlight ((t (:background "#3c3c3c"))))
                        '(region ((t (:background "#6c6c6c"))))
                        '(shadow ((((class color grayscale)
                                    (min-colors 88)
                                    (background light))
                                   (:foreground "grey50"))
                                  (((class color grayscale)
                                    (min-colors 88)
                                    (background dark))
                                   (:foreground "grey70"))
                                  (((class color)
                                    (min-colors 8)
                                    (background light))
                                   (:foreground "green"))
                                  (((class color)
                                    (min-colors 8)
                                    (background dark))
                                   (:foreground "yellow"))))
                        '(secondary-selection ((t (:background "darkslateblue"))))
                        '(trailing-whitespace ((((class color)
                                                 (background light))
                                                (:background "red1"))
                                               (((class color)
                                                 (background dark))
                                                (:background "red1"))
                                               (t (:inverse-video t))))
                        '(font-lock-builtin-face ((t (:foreground "#D0D0FF"))))
                        '(font-lock-comment-delimiter-face ((default (:inherit (font-lock-comment-face)))))
                        '(font-lock-comment-face ((t (:italic t :foreground "#BC9458"))))
                        '(font-lock-constant-face ((t (:foreground "#6D9CBE"))))
                        '(font-lock-doc-face ((t (:inherit (font-lock-string-face)))))
                        '(font-lock-function-name-face ((t (:foreground "#FFC66D"))))
                        '(font-lock-keyword-face ((t (:foreground "#CC7833"))))
                        '(font-lock-negation-char-face ((t nil)))
                        '(font-lock-preprocessor-face ((t (:foreground "#CC7833"))))
                        '(font-lock-regexp-grouping-backslash ((t (:inherit (bold)))))
                        '(font-lock-regexp-grouping-construct ((t (:inherit (bold)))))
                        '(font-lock-string-face ((t (:foreground "#A5C261"))))
                        '(font-lock-type-face ((t (:foreground "#F2777A"))))
                        '(font-lock-variable-name-face ((t (:foreground "LightSteelBlue"))))
                        '(font-lock-warning-face ((t (:foreground "Pink"))))
                        '(button ((t (:inherit (link)))))
                        '(link ((((class color)
                                  (min-colors 88)
                                  (background light))
                                 (:underline (:color foreground-color :style line)
                                             :foreground "RoyalBlue3"))
                                (((class color)
                                  (background light))
                                 (:underline (:color foreground-color :style line)
                                             :foreground "blue"))
                                (((class color)
                                  (min-colors 88)
                                  (background dark))
                                 (:underline (:color foreground-color :style line)
                                             :foreground "cyan1"))
                                (((class color)
                                  (background dark))
                                 (:underline (:color foreground-color :style line)
                                             :foreground "cyan"))
                                (t (:inherit (underline)))))
                        '(link-visited ((default (:inherit (link)))
                                        (((class color)
                                          (background light))
                                         (:foreground "magenta4"))
                                        (((class color)
                                          (background dark))
                                         (:foreground "violet"))))
                        '(fringe ((t (:background "#2b2b2b"))))
                        '(header-line ((default (:inherit (mode-line)))
                                       (((type tty))
                                        (:underline (:color foreground-color :style line)
                                                    :inverse-video nil))
                                       (((class color grayscale)
                                         (background light))
                                        (:box nil :foreground "grey20"
                                              :background "grey90"))
                                       (((class color grayscale)
                                         (background dark))
                                        (:box nil :foreground "grey90"
                                              :background "grey20"))
                                       (((class mono)
                                         (background light))
                                        (:underline (:color foreground-color :style line)
                                                    :box nil
                                                    :inverse-video nil
                                                    :foreground "black"
                                                    :background "white"))
                                       (((class mono)
                                         (background dark))
                                        (:underline (:color foreground-color :style line)
                                                    :box nil
                                                    :inverse-video nil
                                                    :foreground "white"
                                                    :background "black"))))
                        '(tooltip ((((class color))
                                    (:inherit (variable-pitch)
                                              :foreground "black"
                                              :background "lightyellow"))
                                   (t (:inherit (variable-pitch)))))
                        '(mode-line ((t (:box nil :foreground "black"
                                              :background "#A5BAF1"))))
                        '(mode-line-buffer-id ((t (:foreground "black" :background "#A5BAF1"))))
                        '(mode-line-emphasis ((t (:weight bold))))
                        '(mode-line-highlight ((((class color)
                                                 (min-colors 88))
                                                (:box (:line-width 2 :color "grey40"
                                                                   :style released-button)))
                                               (t (:inherit (highlight)))))
                        '(mode-line-inactive ((default (:inherit (mode-line)))
                                              (((class color)
                                                (min-colors 88)
                                                (background light))
                                               (:background "grey90"
                                                            :foreground "grey20"
                                                            :box (:line-width -1 :color "grey75"
                                                                              :style nil):weight
                                                                              light))
                                              (((class color)
                                                (min-colors 88)
                                                (background dark))
                                               (:background "grey30"
                                                            :foreground "grey80"
                                                            :box (:line-width -1 :color "grey40"
                                                                              :style nil):weight
                                                                              light))))
                        '(isearch ((t (:background "#555555"))))
                        '(isearch-fail ((((class color)
                                          (min-colors 88)
                                          (background light))
                                         (:background "RosyBrown1"))
                                        (((class color)
                                          (min-colors 88)
                                          (background dark))
                                         (:background "red4"))
                                        (((class color)
                                          (min-colors 16))
                                         (:background "red"))
                                        (((class color)
                                          (min-colors 8))
                                         (:background "red"))
                                        (((class color grayscale))
                                         (:foreground "grey"))
                                        (t (:inverse-video t))))
                        '(lazy-highlight ((((class color)
                                            (min-colors 88)
                                            (background light))
                                           (:background "paleturquoise"))
                                          (((class color)
                                            (min-colors 88)
                                            (background dark))
                                           (:background "paleturquoise4"))
                                          (((class color)
                                            (min-colors 16))
                                           (:background "turquoise3"))
                                          (((class color)
                                            (min-colors 8))
                                           (:background "turquoise3"))
                                          (t (:underline (:color foreground-color :style line)))))
                        '(match ((((class color)
                                   (min-colors 88)
                                   (background light))
                                  (:background "yellow1"))
                                 (((class color)
                                   (min-colors 88)
                                   (background dark))
                                  (:background "RoyalBlue3"))
                                 (((class color)
                                   (min-colors 8)
                                   (background light))
                                  (:foreground "black" :background "yellow"))
                                 (((class color)
                                   (min-colors 8)
                                   (background dark))
                                  (:foreground "white" :background "blue"))
                                 (((type tty)
                                   (class mono))
                                  (:inverse-video t))
                                 (t (:background "gray"))))
                        '(next-error ((t (:inherit (region)))))
                        '(query-replace ((t (:inherit (isearch))))))
(provide-theme 'railscast-modified)
